### ISSUE TITLE
Way to keep from switching to elfeed-entry buffer?

### ISSUE THREAD

**Issue by seanleblanc** [algernon/elfeed-goodies#12]
Is there something I can set to keep point from switching to the elfeed-entry buffer when I use RET/elfeed-search-show-entry?

**Comment by algernon** [comment]
Hm. I have an idea, will try ~tomorrow.

**Comment by algernon** [comment]
Took a bit longer than expected, because I forgot to come back to it. Sorry about that, added functionality with which it is easy to achieve the desired behaviour!
