### ISSUE TITLE
split pane: highlighted line one entry ahead with elfeed-show-next

### ISSUE THREAD

**Issue by felixpinkert** [algernon/elfeed-goodies#13]
First of all, many thanks for writing elfeed-goodies, I love it and it's a great help.
One problem I'm encountering with the split pane setup: Using elfeed-show-next while in the elfeed-show window, the highlighted line in elfeed-search is always one entry ahead of the one displayed in elfeed-show. I haven't had a close enough look at the code yet to see what causes this, but maybe it's a quick fix. Many thanks again!

**Comment by algernon** [comment]
Yeah, that has been bothering me a while too. It is coming from elfeed itself, the non-split version works like this. It's not a trivial fix, but it's been bugging me too, and now that I know I'm not the only one, that's enough motivation to have a go at fixing it. :)
