### ISSUE TITLE
typo in `elfeed-goodies/split-show-prev'.

### ISSUE THREAD

**Issue by kametoku** [algernon/elfeed-goodies#14]
Pressing "p" in the elfeed-search buffer causes the following error:
Wrong type argument: commandp, elfeed-goodiess/split-search-show-entry

The following line in elfeed-goodies-split-pane.el

> (call-interactively #'elfeed-goodiess/split-search-show-entry)))

should be:

> (call-interactively #'elfeed-goodies/split-search-show-entry)))

Thanks.

**Comment by algernon** [comment]
Oops! Nice catch, fixed on master now. Thanks!
