### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by csantosb** [algernon/elfeed-goodies#18]
When installing from melpa I get the following message

```
Compiling file $HOME/emacs-packages/elpa/elfeed-goodies-20160926.209/elfeed-goodies.el at Mon Sep 26 21:22:20 2016
Entering directory ‘$HOME/emacs-packages/elpa/elfeed-goodies-20160926.209/’
elfeed-goodies.el:26:1:Error: Symbol’s value as variable is void: left
```

Any ideas ? I am using 25.1.

**Comment by algernon** [comment]
Can't reproduce this on 24.5.1 :(

I'll see what I can do over the weekend, if all goes well.

**Comment by csantosb** [comment]
I just checked: this is not an issue any more under emacs 28.0.50
