### ISSUE TITLE
Feature request: use split pane stand-alone

### ISSUE THREAD

**Issue by c-alpha** [algernon/elfeed-goodies#32]
I'd like to be able to use the split pane feature only, i.e. without the powerline-based header or any other eye candy, please.

**Comment by jeetelongname** [comment]
Hi! I would not mind a PR for this, I am currently trying to update and modularise elfeed-goodies so its easier to extend and remove, its just been a little slow going with life and all that.

**Comment by jeetelongname** [comment]
If you do want to do this then do not call `elfeed-goodies/setup` and just add 

```lisp
  (setq elfeed-show-entry-switch #'elfeed-goodies/switch-pane
        elfeed-show-entry-delete #'elfeed-goodies/delete-pane
        elfeed-show-refresh-function #'elfeed-goodies/show-refresh--plain)

  (define-key elfeed-show-mode-map "n" #'elfeed-goodies/split-show-next)
  (define-key elfeed-show-mode-map "p" #'elfeed-goodies/split-show-prev)
```
which should in theory be all that is needed to *just* use that. setup is a set of defaults but you should be able to use as little or as much as you want if you just configure it yourself :)

which should only rebind those keys

**Comment by c-alpha** [comment]
Thanks for the hint! 😄

**Comment by Thaodan** [comment]
> which should in theory be all that is needed to _just_ use that. setup is a set of defaults but you should be able to use as little or as much as you want if you just configure it yourself :)

It might be handy if powerline would be an  optional dependency for such cases.

**Comment by jeetelongname** [comment]
the setup function was always a set of opinionated defaults. You can take as much of this package. I think a new issue / PR for this is warranted.
