### ISSUE TITLE
Replace ace-jump-mode, eliminate cl warning

### ISSUE THREAD

**Issue by Lord-Valen** [algernon/elfeed-goodies#36]
Ace-jump-mode requires cl (deprecated) instead of cl-lib, causing a deprecation warning. In winterTTr/ace-jump-mode#100 the issue was noted. In winterTTr/ace-jump-mode#101 a fix was presented; however, the last commit, winterTTr/ace-jump-mode@8351e2d, was in 2014, and the PR has received no response. As it stands, there is clearly no ongoing effort to maintain ace-jump-mode. Is it possible to use a package with similar functionality like [avy](https://github.com/abo-abo/avy) instead?

**Comment by jeetelongname** [comment]
Hi! yeah I would not mind reviewing and merging a PR! otherwise it will be up to the whim of my schedule / organisation which are both kinda lacking...
