### ISSUE TITLE
Feature Request: define new faces instead of reusing elfeed faces

### ISSUE THREAD

**Issue by brabalan** [algernon/elfeed-goodies#41]
The current reuse of faces from elfeed makes it difficult for theme authors to provide defaults that work well both with elfeed and elfeed-goodies, resulting as issues such as #24. Could it be possible to define new faces instead, taking their initial spec from the corresponding elfeed face? This way one could change the elfeed-goodies face independently of the corresponding elfeed face.

Related discussion on the ef-themes list: https://lists.sr.ht/~protesilaos/ef-themes/%3C87sfll3kxm.fsf%40m4x.org%3E

**Comment by jeetelongname** [comment]
I will happily take a PR for this, Otherwise it may take a bit for me to get around to this
